### ISSUE TITLE
Please Provide a Matrix/Documenation of Breaking Removals/Additions for People Attempting to Migrate

### ISSUE THREAD

**Issue by jlambright** [Aniketkhote/refreshed#9]
In order for potential users to make an informed decision, they need an idea of how much refactoring is ahead of them. Please provide some kind of documentation on which classes/function/properties have been removed.

**Comment by asterd** [comment]
My personal experience on a medium-sized app: you have just to follow the draft migration guide (https://github.com/jonataslaw/getx/issues/2966) since it is based on getx 5 branch. In addition, he choose to remove minor extension methods (like padding and others) to the quickly package. It's a little bit annoying to migrate if you have used it a lot, but is also pretty simple. My migration requires no more than one afternoon (for a project with around 60k lines of code).
